name: Production CI Pipeline on main branch

  # Trigger workflow on push request to the development branch
on:
  push:
    branches:
      - "main"
    
jobs:
  call-reusable:
    name: Call Reusable Next.js CI Workflow
    # or use the shared repo like uses: your-org/shared-repo/.github/workflows/nextjs-reusable-ci.yml@main
    # uses: ./.github/workflows/reuseablenext-workflow.yml
    uses: ./.github/workflows/reuseable-workflow.yml
    with:
      node-version: '22'
      environment_name: 'production'
    secrets: inherit # This allows the reusable workflow to access secrets from the calling workflow's repository. Make sure to set the required secrets in the repository settings.